sudo: required

notifications:
  slack:
    secure: KUR1h3HY3LoLTH+lOCijT2MssuwEFIVt9bu1+p6t1CK1Zj6aWOWO5lqN8VIwngljx//isYDLj09nrmmg3ikrT/r29feolgSaw74l4qDICTWlfpWmtPcskMM8Cp7OKf5kq1ZolqbcI8sThBK/6Fln3pmm1Rxbh+xnaJSksBMOCyvjBkA7jTTedM1LNHllaBkV7d42KtrHEcVay2BXWZSBzOBUkFguxwoCZ5nfuppS9O6EaPTusDFvPekkyR7+NidaTDIvEW9IsQ0yuug6vJNGDlKo3R+Ul+lrOaH3af7PX+4TiXfzx+G/bvsVR29GsIY7xr+Ckr/KkW3qknN0Aezsl7xk2UuDElQ0qgpBBfZ4PSkuKXqT98xPkWHBsuPepNF/4TGY7tfjPm+p2lXBo6oW6wqXmKQmpLGSXdHxo5FDAs86g/sZl1QY/WpUu5FznIVhETHlqTpNc2aH6bCaVJ98JTKUgLAVfBSF7IIAPBI6tUIaReghJCGPW+0Wb3AatZSl3rp5Gm2yktXSfBlEv2otfUB8SGPuISX//CQ6qlSv2Y+hdxGzVvAGyhfVTmPwSfhYI0vtvaQGH1C8trA6cnTm3W0Ubb24vqqpzY8Jw/4adbHkBY0k7+IHz4LhAt+3H9poIaRGWoJPkimt3DLYX/a8BK79cmgnViXRNCBzUxRkRi8=
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    # Build App
    - name: "Build app"
      language: android
      jdk: oraclejdk8
      env:
        global:
        - ANDROID_API=27
        - ANDROID_BUILD_TOOLS=28.0.3
      addons:
        apt_packages:
        - pandoc
      android:
        components:
        - tools
        - platform-tools
        - build-tools-$ANDROID_BUILD_TOOLS
        - android-$ANDROID_API
        licenses:
        - android-sdk-preview-license-52d11cd2
        - android-sdk-license-.+
        - google-gdk-license-.+
      before_cache:
      - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
        - app/node_modules
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
      before_install:
      - nvm install 7
      - node --version
      - mkdir -p $ANDROID_HOME/licenses
      - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
      - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
      - yes | sdkmanager "platforms;android-27"
      - touch /home/travis/.android/repositories.cfg
      - openssl aes-256-cbc -K $encrypted_ac356ff71e5e_key -iv $encrypted_ac356ff71e5e_iv -in buildFiles.tar.enc -out buildFiles.tar -d
      - ./scripts/extract.sh
      install:
      - cd app
      - npm install
      script:
      - npm run build-release
      deploy:
        # Deploy app
        #provider: releases
        #file: app/build/outputs/apk/release/app-release.apk
        #skip_cleanup: true
        #api-key: $GITHUB_TOKEN
        #on:
        #  all_branches: true
        #  condition: $TRAVIS_BRANCH =~ ^master|develop$
        #  repo: Mavionics/missionControl
        #  jdk: oraclejdk8

    - name: Build website 
      language: node_js
      node_js:
      - 8

      ## Cache NPM folder and Cypress binary
      ## to avoid downloading Cypress again and again
      cache:
        directories:
          - ~/.npm
          - ~/.cache

      install:
      - cd mavionics
      - npm install
      - npm ci
      - npm install -g firebase-tools
      script:
      - npm run test:unit
      #- $(npm bin)/cypress run
      - ./../scripts/build.sh
