sudo: required

notifications:
  slack:
    secure: KUR1h3HY3LoLTH+lOCijT2MssuwEFIVt9bu1+p6t1CK1Zj6aWOWO5lqN8VIwngljx//isYDLj09nrmmg3ikrT/r29feolgSaw74l4qDICTWlfpWmtPcskMM8Cp7OKf5kq1ZolqbcI8sThBK/6Fln3pmm1Rxbh+xnaJSksBMOCyvjBkA7jTTedM1LNHllaBkV7d42KtrHEcVay2BXWZSBzOBUkFguxwoCZ5nfuppS9O6EaPTusDFvPekkyR7+NidaTDIvEW9IsQ0yuug6vJNGDlKo3R+Ul+lrOaH3af7PX+4TiXfzx+G/bvsVR29GsIY7xr+Ckr/KkW3qknN0Aezsl7xk2UuDElQ0qgpBBfZ4PSkuKXqT98xPkWHBsuPepNF/4TGY7tfjPm+p2lXBo6oW6wqXmKQmpLGSXdHxo5FDAs86g/sZl1QY/WpUu5FznIVhETHlqTpNc2aH6bCaVJ98JTKUgLAVfBSF7IIAPBI6tUIaReghJCGPW+0Wb3AatZSl3rp5Gm2yktXSfBlEv2otfUB8SGPuISX//CQ6qlSv2Y+hdxGzVvAGyhfVTmPwSfhYI0vtvaQGH1C8trA6cnTm3W0Ubb24vqqpzY8Jw/4adbHkBY0k7+IHz4LhAt+3H9poIaRGWoJPkimt3DLYX/a8BK79cmgnViXRNCBzUxRkRi8=
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    # Build App
    - name: "Build app"
      language: ruby
      services:
        - docker
      before_cache:
      - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
        - app/node_modules
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
      before_install:
      - gem update --system
      - gem install fastlane
      - openssl aes-256-cbc -K $encrypted_f27fbffeb2d3_key -iv $encrypted_f27fbffeb2d3_iv -in buildFiles.tar.enc -out buildFiles.tar -d
      - ./scripts/extract.sh
      - docker pull owodunni/mavionics-android:0.1.0
      install:
      script:
      - docker run --rm -v "$PWD":/root/tmp -w /root/tmp/app owodunni/mavionics-android:0.1.0 /bin/sh -c "npm install; npm run build-release"
      - ./../scripts/deployApp.sh

    - name: Build website 
      language: node_js
      node_js:
      - 8

      ## Cache NPM folder and Cypress binary
      ## to avoid downloading Cypress again and again
      cache:
        directories:
          - ~/.npm
          - ~/.cache

      install:
      - cd mavionics
      - npm install
      - npm ci
      - npm install -g firebase-tools
      script:
      - npm run test:unit
      #- $(npm bin)/cypress run
      - ./../scripts/build.sh
